### ISSUE TITLE
Ags: Missing icons 

### ISSUE THREAD

**Issue by daniel-hernandez-sony** [end-4/CirnOS#2]
You have a beautiful masterpiece of an `ags` configuration, sir. Thank you so much for the inspiration. I hope it does not bother you that I am opening up an issue on this.

### Issue

I am seeing an issue where `ags` does not seem to be finding icons:

![image](https://github.com/end-4/CirnOS/assets/118762057/cc7fcb6c-7d8b-4adc-8859-8c8509d23ce2)

The logs from `ags` don't seem to indicate that there is an issue with icons:

```
Gjs-Console-Message: 15:06:19.963: [LOG] Styles loaded

(com.github.Aylur.ags:13308): Gjs-Console-WARNING **: 15:06:19.988: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))

(com.github.Aylur.ags:13308): Gjs-Console-WARNING **: 15:06:20.111: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))

(com.github.Aylur.ags:13308): Gjs-Console-WARNING **: 15:06:20.181: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))

(com.github.Aylur.ags:13308): Gjs-Console-WARNING **: 15:06:20.225: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))

(com.github.Aylur.ags:13308): Gjs-Console-WARNING **: 15:06:20.254: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))

(com.github.Aylur.ags:13308): Gjs-Console-WARNING **: 15:06:20.274: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))

(com.github.Aylur.ags:13308): Gjs-Console-WARNING **: 15:06:20.328: passing the config object with default export is DEPRECATED. use App.config() instead
```

### What I have done

I am trying to copy over your `ags` config to my nixos / home-manager set up. To do so I have:
- Copied your `ags/default.nix`
- Enabled `programs.ags.enable = true` (which is already present in your config).
- Ensured that the entire `ags/` directory is in `~.config/ags/`.

Let me know if I am missing something (i.e some icon package that gets installed elsewhere in your nix config), or if you would like to provide more info on the issue.

**Comment by end-4** [comment]
This is not maintained since I no longer use NixOS, and my knowledge unfortunately isn't there yet to fully support you
As a level 1 rookie in Nix I can only say everything you've done sounds alright and I'm clueless

**Comment by end-4** [comment]
Actually I'm going to do a bit of further guessing
- Have you added Material Symbols to your system? Those icons rely on that font
- Not about icons, but looks like you're using the latest AGS version but old version of my AGS config. Copy the AGS folder from my [dotfiles repo](https://github.com/end-4/dots-hyprland) for the latest so it doesn't show deprecated messages

**Comment by daniel-hernandez-sony** [comment]
It was actually the material symbols! I had the feeling that it was something related to icons but I don't a lot of knowledge about how icon packs are used in nixOS / Linux in general.

Thank you for pointing at the more recent version :) . I did change some code manually to get rid of warnings but having an alltogether more modern version is a better idea. 

Once again, nice job on your setup (and thank you)
