### ISSUE TITLE
Will this be updated?

### ISSUE THREAD

**Issue by eqfae** [end-4/CirnOS#3]
![图片](https://github.com/user-attachments/assets/bb39e713-12a8-4840-84b2-247782fcc2f2)
![图片](https://github.com/user-attachments/assets/0f809220-341e-4dc6-8502-4614945ec6f7)
https://github.com/end-4/dots-hyprland
This is the best looking desktop I've ever seen.

**Comment by end-4** [comment]
I have stopped using NixOS since I find it not worth the effort, so this repo won't be updated

**Comment by eqfae** [comment]
> I have stopped using NixOS since I find it not worth the effort, so this repo won't be updated

Why? I was attracted by its stability and reproducibility.

**Comment by end-4** [comment]
Too much work. Not for me. I have only one device.
There's no such thing as stability on Linux desktop.
